version: "3.8"

services:
  spring-app:
    image: maksyuze456/easeport:staging
    container_name: easeport-staging
    working_dir: /app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mysql
    command: mvn spring-boot:run

  mysql:
    image: mysql:8.0
    container_name: easeport-mysql-server
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

