version: "3.8"

services:
  spring-app:
    image: maksyuze456/easeport:latest
    container_name: easeport-prod
    working_dir: /app
    ports:
      - "8443:8443"
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - /opt/certs/easeport/origin.p12:/etc/ssl/easeport/origin.p12:ro
    command: mvn spring-boot:run

  mysql:
    image: mysql:8.0
    container_name: easeport-mysql-server
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

