name: Spring Boot Staging CD

on:
  push:
    tags:
      - 's*'
    branches:
      - staging
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: '21'

jobs:

  # Job 1: Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify -B

      - name: Cache target directory
        uses: actions/cache@v3
        with:
          path: target
          key: build-${{ github.sha }}

  # Deploy to staging server
  # Build and push docker image
  docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:staging
            ${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}

  deploy:
    name: Deploy on Hetzner VM
    runs-on: ubuntu-latest
    needs: [ docker-image ]
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy Docker Compose files
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml .env ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/springapp/

      - name: Build & Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd ~/springapp
          docker compose --project-name easeport_backend_staging down
          docker compose pull
          docker compose --project-name easeport_backend_staging up -d
          docker system prune -f
          EOF
